language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5.0b3"
  - "3.5-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.5.0b3"
    - python: "3.5-dev"
    - python: "nightly"

install: "pip install ipython pyflakes"

script:
  - shopt -s extglob globstar
  - py.test
  - pyflakes iterm2_tools/**/!(__init__).py setup.py

sudo: false
