language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.5-dev"
    - python: "nightly"

install: "pip install ipython==4.1.1 pyflakes==1.0.0"

before_install:
  - pip install coverage==4.0.3 codecov==1.6.3 pytest-cov
after_success:
  - codecov

script:
  - shopt -s extglob globstar
  - py.test --cov=./
  - pyflakes iterm2_tools/**/!(__init__).py setup.py

sudo: false
